### ISSUE TITLE
Person name news

### ISSUE THREAD

**Issue by tymees** [uscki/appcki-native-android#18]
Op het moment word de poster altijd null null. Kortom, er wordt een niet bestaand veld er neer gezet.

Nou ga ik niet de schuld bij de app leggen, tenminste, niet helemaal. De error komt door het overschakelen van de PersonSimpleBean naar de PersonNameBean. Deze laatste bevat de velden ``firstname``, ``middlename`` en ``lastname``. niet. Ik vermoed dan ook dat deze velden gebruikt worden door de app.

En hier komt het 'niet helemaal' gedeelte: deze velden hadden ook nooit gebruikt moeten worden hiervoor. Deze velden zijn eigenlijk alleen voor de ledenadministratie (en smobo, maar das een ander verhaal). Wat gebruikt had moeten worden was 'postalname'. Uit de API documentatie: 

> Postal name, often identical to Firstname + Middlename + Lastname, but can be modified to include a name that's funnier or a 'roepnaam'. This should be the preferred name in agenda, news, and the sort. Don't manually stitch together the users full name. - https://www.uscki.nl/~mees/dev-docs.php

**TL;DR**
Verander de veld voor naam bij news naar ``postalname`` uit de API, het gaat nu heerlijk fout

**Comment by blackwolf12333** [comment]
Yeah klopt, ik had idd eerst in de person bean een functie die first middle en last name aan elkaar plakte. Omdat postal name nog niet een ding was geloof ik. Zal t aanpassen om postalname te gebruiken.
